name: Bygg og deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  buildDev:
    uses: navikt/aap-workflows/.github/workflows/frontend-next-build.yml@main
    permissions:
      contents: read
      id-token: write
      packages: write
    secrets: inherit
    with:
      cluster: dev-gcp
      appname: 'aap-paw-patrol'
      playwright: false
      cdn: true

  buildProd:
    uses: navikt/aap-workflows/.github/workflows/frontend-next-build.yml@main
    permissions:
      contents: read
      id-token: write
      packages: write
    secrets: inherit
    with:
      cluster: prod-gcp
      appname: 'aap-paw-patrol'
      playwright: false
      cdn: true

  deployDev:
    needs: buildDev
    uses: navikt/aap-workflows/.github/workflows/deploy.yml@main
    permissions:
      contents: read
      id-token: write
    secrets: inherit
    with:
      cluster: dev-gcp
      manifest: .nais/nais.yaml
      imageSuffix: -dev-gcp
      vars: .nais/dev.yaml

  deployProd:
    needs: deployDev
    uses: navikt/aap-workflows/.github/workflows/deploy.yml@main
    permissions:
      contents: read
      id-token: write
    secrets: inherit
    with:
      cluster: prod-gcp
      manifest: .nais/nais.yaml
      imageSuffix: -prod-gcp
      vars: .nais/prod.yaml
